CREATE DATABASE java07;
USE java07;
CREATE TABLE student(
`id` INT(11) NOT NULL AUTO_INCREMENT,
`sno` VARCHAR(20) NOT NULL COMMENT '学号',
`name` VARCHAR(10) NOT NULL COMMENT '姓名',
`gender` TINYINT DEFAULT 0 COMMENT '1-男,2-女',
`term_id` INT(11) NOT NULL,
PRIMARY KEY (`id`)
)ENGINE= INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;

CREATE TABLE term(
`id` INT(11) NOT NULL AUTO_INCREMENT,
`cno` INT(11) NOT NULL COMMENT '班级编号',
`name` VARCHAR(10) NOT NULL COMMENT '班级姓名',
PRIMARY KEY (`id`)
)ENGINE= INNODB DEFAULT CHARSET=utf8;

CREATE TABLE course(
`id` INT(11) NOT NULL AUTO_INCREMENT,
`course_no` INT(11) NOT NULL COMMENT '课程编号',
`name` VARCHAR(10) NOT NULL COMMENT '课程名称',
`type` TINYINT NOT NULL COMMENT '1-必修，2-选修',
PRIMARY KEY (`id`)
)ENGINE= INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;

CREATE TABLE score(
`id` INT(11) NOT NULL AUTO_INCREMENT,
`stu_id` INT(11) NOT NULL COMMENT '学生id',
`cou_id` INT(11) NOT NULL COMMENT '课程id',
`score` INT(11) NOT NULL COMMENT '分数',
PRIMARY KEY (`id`)
)ENGINE= INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;